version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    mem_limit: 1g

    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: bot
      MYSQL_USER: bot
      MYSQL_PASSWORD: bot123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -ubot -p$$MYSQL_PASSWORD --silent || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  python:
    build: ./python
    container_name: py-server
    restart: always

    ports:
      - "9812:9812"

  bot:
    build:
      context: .
      dockerfile: DockerFile

    container_name: bot
    restart: always

    depends_on:
      mysql:
        condition: service_healthy
      python:
        condition: service_started

    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}

      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: bot
      DB_PASS: bot123
      DB_NAME: bot

      PYTHON_API: http://python:9812

volumes:
  mysql_data:
