version: "3.8"

services:
  bot:
    build: .
    container_name: bot
    restart: always
    environment:
      - DISCORD_BOT_TOKEN=${secrets.DISCORD_BOT_TOKEN}
    volumes:
      - ~/database.db:/app/database/database.db
    depends_on:
      - python

  python:
    build: ./python
    container_name: py-server
    restart: always
    ports:
      - "9812:9812"